[project]
name = "srm-toolkit"
version = "0.0.1"
readme = "README.md"
requires-python = ">= 3.11"
dependencies = []

[tool.black]
line-length = 120

[tool.yapf]
BASED_ON_STYLE = "pep8"

[tool.uv.sources]
srm-cli = { workspace = true }

[tool.uv.workspace]
members = [
    "packages/*",
]
exclude = [
    "scripts-blender/*"
]
